[workspace]
resolver = "3"

members = [
    "firmware",
    "shared",
    "browser"
]

[profile.dev]
opt-level = "z"
lto = true
panic = "abort"

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
debug = 2

[profile.release-mini]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = 0
