[package]
name = "rigToUsb"
version = "0.1.0"
edition = "2024"

[dependencies]
nb = "1"
stm32g4 = { version = "0.16.0", features = ["atomics"] }
paste = "1.0"
fugit = "0.3.7"
stm32-usbd = { version = "0.7.0" }
fixed = { version = "1.28.0", optional = true }
embedded-io = "0.6"
stm32-hrtim = { version = "0.1.0", optional = true }
rand_core = { version = "0.9", default-features = false }
usb-device = { version = "0.3.2", features = ["defmt", "control-buffer-256"] }
cortex-m-rt = "0.7.2"
usbd-serial = "0.2.2"
usbd-audio = "0.4"
usbd-hid = "0.10.0"
cfg-if = "1.0"
panic-halt = "0.2"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
log = { version = "0.4.11" }
defmt-rtt = "0.4.0"
minicbor = { version = "0.24", features = ["derive"] }

[features]
log-itm = []
log-semihost = []

[dependencies.cortex-m]
version = "0.7.7"
features = ["critical-section-single-core"]

[dependencies.stm32g4xx-hal]
version = "0.1.0"
features = [
  "stm32g474",
  "log-rtt",
  "defmt",
  "usb",
  "rt"]

[dependencies.fdcan]
version = "0.2.1"
features = ["fdcan_g0_g4_l5"]
optional = true

[dependencies.cast]
version = "0.2.7"
default-features = false

[dependencies.embedded-hal-old]
package = "embedded-hal"
features = ["unproven"]
version = "0.2.7"

[dependencies.embedded-hal]
version = "1.0.0"

[dependencies.embedded-dma]
version = "0.1.2"

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.defmt]
version = "1"
optional = true

[dev-dependencies]
cortex-m-rt = "0.7.2"
defmt-rtt = "0.4.0"
embedded-test = "0.6.2"
cortex-m-rtic = "1.1.4"
cortex-m-semihosting = "0.3.5"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
panic-semihosting = "0.5.3"
panic-halt = "0.2.0"
panic-itm = "0.4.2"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
log = "0.4.11"
cortex-m-log = { version = "0.7", features = ["log-integration"] }
cfg-if = "0.1.10"
mpu6050 = "0.1.4"
bme680 = "0.6.0"
embedded-sdmmc = "0.3.0"
usb-device = { version = "0.3.2", features = ["defmt", "control-buffer-256"] }
usbd-serial = "0.2.2"
usbd-audio = "0.4"
rand = { version = "0.9", default-features = false }

[profile.dev]
codegen-units = 1
debug = true
incremental = false
lto = false

[profile.release]
debug = false
codegen-units = 1
incremental = false
lto = true

[profile.test]
opt-level = "s"
debug = true
codegen-units = 1
incremental = false
lto = true

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "hid-raw"
path = "src/hid-raw.rs"
