use minicbor::{Decode, Encode};
use minicbor::encode::write::Cursor;
use defmt_rtt as _;

#[derive(defmt::Format)]
#[derive(Decode, Encode, Debug)]
#[cbor(flat)]
pub enum MessageIn {
    #[n(0)]
    Success{#[n(0)] value: u32},
    #[n(1)]
    Error {
        #[n(0)] code: u32,
        #[n(1)] message: u32,
    },    
}

pub fn message_example() {
    defmt::info!("--- CBOR Test mit defmt gestartet ---");

    let mut tx_buffer1 = [0u8; 64];
    let mut cursor1 = Cursor::new(&mut tx_buffer1[..]);
    let msg_success = MessageIn::Success{value:42};
    defmt::info!("1. Teste: {:?}", msg_success);
    if let Ok(_encoded_s) = minicbor::encode(&msg_success, &mut cursor1) {
        let bytes_written = cursor1.position();
        let encoded_slice = &tx_buffer1[..bytes_written];
        defmt::info!("   -> Generated Bytes: {=[u8]:x}", encoded_slice);

        if let Ok(decoded) = minicbor::decode::<MessageIn>(encoded_slice) {
            defmt::info!("   -> Dekodiert erfolgreich: {:?}", decoded);
        } else {
            defmt::error!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    defmt::info!("--------------------------------------------------");

    let mut tx_buffer2 = [0u8; 64];
    let mut cursor2 = Cursor::new(&mut tx_buffer2[..]);

    let msg_error = MessageIn::Error { code: 5, message: 100 };
    defmt::info!("2. Teste: {:?}", msg_error);

    if let Ok(_encoded_s) = minicbor::encode(&msg_error, &mut cursor2) {
        let bytes_written = cursor2.position();
        let encoded_slice = &tx_buffer2[..bytes_written];
        defmt::info!("   -> Generated Bytes: {=[u8]:x}", encoded_slice);

        if let Ok(decoded) = minicbor::decode::<MessageIn>(encoded_slice) {
            defmt::info!("   -> Dekodiert erfolgreich: {:?}", decoded);
        } else {
            defmt::error!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    defmt::info!("--------------------------------------------------");
}
