use minicbor::{Decode, Encode};
use minicbor::encode::write::Cursor;
use defmt_rtt as _;
use stm32g4xx_hal::gpio::PinState;

use crate::firmware::bootloader::jump_to_st_bootloader;
use crate::firmware::init::{BoardPeripherals};

#[derive(defmt::Format)]
#[derive(Decode, Encode, Debug)]
#[cbor(flat)]
pub enum Cmd {
    #[n(0)]
    StartBootLoader(),
    #[n(1)]
    LED{#[n(0)] value: bool},
    #[n(2)]
    Success{#[n(0)] value: u32},
    #[n(3)]
    Error {
        #[n(0)] code: u32,
        #[n(1)] message: u32,
    },
}
use Cmd::*;

pub fn message_example() {
    defmt::info!("--- CBOR Test mit defmt gestartet ---");

    let mut tx_buffer1 = [0u8; 64];
    let mut cursor1 = Cursor::new(&mut tx_buffer1[..]);
    let msg_success = Success{value:42};
    defmt::info!("1. Teste: {:?}", msg_success);
    if let Ok(_encoded_s) = minicbor::encode(&msg_success, &mut cursor1) {
        let bytes_written = cursor1.position();
        let encoded_slice = &tx_buffer1[..bytes_written];
        defmt::info!("   -> Generated Bytes: {=[u8]:x}", encoded_slice);

        if let Ok(decoded) = minicbor::decode::<Cmd>(encoded_slice) {
            defmt::info!("   -> Dekodiert erfolgreich: {:?}", decoded);
        } else {
            defmt::error!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    defmt::info!("--------------------------------------------------");

    let mut tx_buffer2 = [0u8; 64];
    let mut cursor2 = Cursor::new(&mut tx_buffer2[..]);

    let msg_error = LED { value: false};
    defmt::info!("2. Teste: {:?}", msg_error);

    if let Ok(_encoded_s) = minicbor::encode(&msg_error, &mut cursor2) {
        let bytes_written = cursor2.position();
        let encoded_slice = &tx_buffer2[..bytes_written];
        defmt::info!("   -> Generated Bytes: {=[u8]:x}", encoded_slice);

        if let Ok(decoded) = minicbor::decode::<Cmd>(encoded_slice) {
            defmt::info!("   -> Dekodiert erfolgreich: {:?}", decoded);
        } else {
            defmt::error!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    defmt::info!("--------------------------------------------------");
}

pub fn decode_and_run(
    board_peripherals: &mut BoardPeripherals,
    packet: &[u8]
)
{
    let mut decoder = minicbor::Decoder::new(&packet);
    if let Ok(cmd) = decoder.decode::<Cmd>() {
	defmt::info!("cbor decode message: {}", cmd);
	run_cmd(board_peripherals,cmd);
    } else
    {
    defmt::info!("cbor decode error");
    defmt::info!("cbor decode daten: {=[u8]:x}", packet);
    defmt::info!("cbor decode daten: {}", packet);
    }
}

pub fn run_cmd(
    board_peripherals: &mut BoardPeripherals,
    cmd: Cmd
)
{
    match cmd {
	StartBootLoader() => {jump_to_st_bootloader();}
	LED{ value } => {board_peripherals.led.set_state(PinState::from(value));}
	Error { code: _, message: _ } => {}
	Success { value:_ } => {jump_to_st_bootloader();}
    }
}
