[package]
name = "rig_to_usb_logic"
version = "0.1.0"
edition = "2024"

[features]
default = []
defmt = ["dep:defmt"]
std-json = ["dep:serde", "dep:serde_json", "minicbor/alloc"]

[dependencies]
minicbor = { version = "2.2", features = ["derive"] }
defmt = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true}
serde_json = { version = "1.0", optional = true }

[[bin]]
name = "stdin_to_cbor"
path = "src/stdin_to_cbor.rs"
