use minicbor::{Decode, Encode};
#[cfg(any(feature = "std-json", feature = "defmt"))]
use minicbor::encode::write::Cursor;

#[cfg(feature = "defmt")]
pub use defmt::{info, warn, error};

#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Decode, Encode, Debug)]
#[cbor(flat)]
#[cfg_attr(feature = "std-json", derive(serde::Deserialize))]
#[cfg_attr(feature = "std-json", serde(rename_all = "lowercase"))]
pub enum Cmd<'a> {
    #[n(0)]
    StartBootLoader, // Keep StartBootLoader at n(0)
    #[n(1)]
    Panic,
    #[n(2)]
    Test,
    #[n(3)]
    Reset,
    #[n(4)]
    LED{#[n(0)] value: bool},
    #[n(5)]
    LEDBlink{#[n(0)] interval: u16},
    #[n(6)]
    RadioOn{#[n(0)] time: u32},
    #[n(7)]
    RadioOff,
    #[n(8)]
    TxOn{#[n(0)] time: u32},
    #[n(9)]
    TxOff,
    #[n(10)]
    MorseSpeed{#[n(0)] ditlen: u16},
    #[n(11)]
    MorseSend{ #[cbor(n(0), with = "minicbor::bytes")] txt: &'a [u8]},
    #[n(12)]
    MorseAppend{ #[cbor(n(0), with = "minicbor::bytes")] txt: &'a [u8]},
    #[n(13)]
    SendCat{ #[cbor(n(0), with = "minicbor::bytes")] bytes: &'a [u8]},
}

#[cfg(any(feature = "std-json", feature = "defmt"))]
pub fn encode_test(cmd: Cmd)
-> ()
{
    let mut tx_buffer1 = [0u8; 64];
    let mut cursor1 = Cursor::new(&mut tx_buffer1[..]);
    match minicbor::encode(&cmd, &mut cursor1) {
	Ok(_) => {
            let bytes_written = cursor1.position();
            let encoded_slice = &tx_buffer1[..bytes_written];
            info!("Encoded: {=[u8]:x}", encoded_slice);
            println!("Encoded: {:?}", encoded_slice);
        }
	Err(_err) => {
//            info!("Encode Error: {}", err);
            println!("Encoded Error");

	}
    }
}

/*
pub fn decode_test
(
    packet: &[u8]
)
-> ()
{
    let mut decoder = minicbor::Decoder::new(&packet);
    match decoder.decode::<Cmd>() {
	Ok(cmd) => {
            defmt::info!("cbor decode message: {}", cmd);
	}
	Err(_err) => {
	    defmt::info!("cbor decode error");
	    defmt::info!("cbor decode daten: {=[u8]:x}", packet);
	    defmt::info!("cbor decode daten: {}", packet);
	}
    }
}



pub fn cbor_message_test() {
    info!("--- CBOR Test ---" );
    println!("--- CBOR Test ---" );    

    let mut tx_buffer1 = [0u8; 64];
    let mut cursor1 = Cursor::new(&mut tx_buffer1[..]);
    let msg_success = Test;
    info!("1. Teste: {:?}", msg_success);
    println!("1. Teste: {:?}", msg_success);    
    if let Ok(_encoded_s) = minicbor::encode(&msg_success, &mut cursor1) {
        let bytes_written = cursor1.position();

        if let Ok(decoded) = minicbor::decode::<Cmd>(encoded_slice) {
            info!("   -> Dekodiert erfolgreich: {:?}", decoded);
            println!("   -> Dekodiert erfolgreich: {:?}", decoded);	    
        } else {
            error!("   -> Dekodierung fehlgeschlagen!");
            println!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    info!("--------------------------------------------------");

    let mut tx_buffer2 = [0u8; 64];
    let mut cursor2 = Cursor::new(&mut tx_buffer2[..]);

    let msg_error = LED { value: false};
    info!("2. Teste: {:?}", msg_error);

    if let Ok(_encoded_s) = minicbor::encode(&msg_error, &mut cursor2) {
        let bytes_written = cursor2.position();
        let encoded_slice = &tx_buffer2[..bytes_written];
        info!("   -> Generated Bytes: {=[u8]:x}", encoded_slice);
        println!("   -> Generated Bytes: {:?}", encoded_slice);
        if let Ok(decoded) = minicbor::decode::<Cmd>(encoded_slice) {
            info!("   -> Dekodiert erfolgreich: {:?}", decoded);
            println!("   -> Dekodiert erfolgreich: {:?}", decoded);
        } else {
            error!("   -> Dekodierung fehlgeschlagen!");
            println!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    info!("--------------------------------------------------");
}

*/
