use minicbor::encode::write::Cursor;
use minicbor::{Decode, Encode};

#[cfg(feature = "defmt")]
pub use defmt::{info, warn, error};

#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Decode, Encode, Debug)]
#[cbor(flat)]
pub enum Cmd {
    #[n(0)]
    StartBootLoader(),
    #[n(1)]
    LED{#[n(0)] value: bool},
    #[n(2)]
    Test(),
    #[n(3)]
    TxOn{#[n(0)] time: u32},
}

use Cmd::*;

pub fn cbor_message_test() {
    info!("--- CBOR Test ---" );
    println!("--- CBOR Test ---" );    

    let mut tx_buffer1 = [0u8; 64];
    let mut cursor1 = Cursor::new(&mut tx_buffer1[..]);
    let msg_success = Test();
    info!("1. Teste: {:?}", msg_success);
    println!("1. Teste: {:?}", msg_success);    
    if let Ok(_encoded_s) = minicbor::encode(&msg_success, &mut cursor1) {
        let bytes_written = cursor1.position();
        let encoded_slice = &tx_buffer1[..bytes_written];
        info!("   -> Generated Bytes: {=[u8]:x}", encoded_slice);
        println!("   -> Generated Bytes: {:?}", encoded_slice);	

        if let Ok(decoded) = minicbor::decode::<Cmd>(encoded_slice) {
            info!("   -> Dekodiert erfolgreich: {:?}", decoded);
            println!("   -> Dekodiert erfolgreich: {:?}", decoded);	    
        } else {
            error!("   -> Dekodierung fehlgeschlagen!");
            println!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    info!("--------------------------------------------------");

    let mut tx_buffer2 = [0u8; 64];
    let mut cursor2 = Cursor::new(&mut tx_buffer2[..]);

    let msg_error = LED { value: false};
    info!("2. Teste: {:?}", msg_error);

    if let Ok(_encoded_s) = minicbor::encode(&msg_error, &mut cursor2) {
        let bytes_written = cursor2.position();
        let encoded_slice = &tx_buffer2[..bytes_written];
        info!("   -> Generated Bytes: {=[u8]:x}", encoded_slice);
        println!("   -> Generated Bytes: {:?}", encoded_slice);
        if let Ok(decoded) = minicbor::decode::<Cmd>(encoded_slice) {
            info!("   -> Dekodiert erfolgreich: {:?}", decoded);
            println!("   -> Dekodiert erfolgreich: {:?}", decoded);
        } else {
            error!("   -> Dekodierung fehlgeschlagen!");
            println!("   -> Dekodierung fehlgeschlagen!");
        }
    }
    info!("--------------------------------------------------");
}
